
const C=window.EMYFIT_CONFIG||{};
let cloud=null,currentUser=null,screen='home',authMode='login',wizardStep=0,restTimer=null,restSeconds=0;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const icon=n=>`<svg class="icon"><use href="#i-${n}"></use></svg>`;
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>crypto.randomUUID?.()||Math.random().toString(36).slice(2);
const fmt=d=>new Date(d+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'short'});
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));

const EVIDENCE={
 acsm:{title:'ACSM Position Stand — Resistance Training (2026)',note:'A programação prioriza regularidade, esforço adequado, progressão e trabalho dos grandes grupos musculares; complexidade não substitui consistência.',url:'https://acsm.org/resistance-training-guidelines-update-2026/'},
 who:{title:'WHO Guidelines on Physical Activity',note:'A meta de cardio é progressiva e considera a recomendação populacional de 150–300 min/semana de atividade moderada, respeitando tolerância individual.',url:'https://www.who.int/publications/i/item/9789240015128'},
 obesity:{title:'Lopez et al. — Systematic review and meta-analysis',note:'Programas baseados em treinamento resistido podem melhorar composição corporal em pessoas com sobrepeso ou obesidade, especialmente em abordagem multicomponente.',url:'https://pubmed.ncbi.nlm.nih.gov/35191588/'},
 knee:{title:'Resistance training and knee symptoms — systematic reviews',note:'Fortalecimento pode integrar o manejo de sintomas e função, mas dose, amplitude e seleção precisam ser individualizadas e interrompidas diante de sinais de alerta.',url:'https://pubmed.ncbi.nlm.nih.gov/38980284/'}
};

const EX={
 legpress:{name:'Leg press 45°',media:'legpress.svg',machine:'Leg press inclinado',pattern:'Extensão de joelho e quadril',primary:['quadríceps','glúteos'],level:'iniciante',knee:'adapt',back:'adapt',sets:3,reps:'10–15',rest:90,cues:['Pés estáveis na plataforma','Joelhos acompanham a direção dos pés','Mantenha lombar e pelve apoiadas','Use amplitude sem dor'],avoid:['dor forte','travamento','perda do apoio lombar'],why:'Máquina guiada com fácil controle de carga e amplitude.',subs:['legpressh','extension','hip'],source:'acsm'},
 legpressh:{name:'Leg press horizontal',media:'legpress_h.svg',machine:'Leg press horizontal',pattern:'Extensão de joelho e quadril',primary:['quadríceps','glúteos'],level:'iniciante',knee:'adapt',back:'adapt',sets:3,reps:'10–15',rest:90,cues:['Banco ajustado para não fechar demais o joelho','Lombar apoiada','Retorno controlado'],avoid:['dor forte','pelve descolando'],why:'Alternativa guiada com posição sentada e controle de amplitude.',subs:['legpress','extension'],source:'knee'},
 extension:{name:'Cadeira extensora',media:'extension.svg',machine:'Cadeira extensora',pattern:'Extensão de joelho',primary:['quadríceps'],level:'iniciante',knee:'adapt',back:'ok',sets:3,reps:'12–15',rest:75,cues:['Alinhe o eixo da máquina ao joelho','Não chute a carga','Segure brevemente no topo','Retorne em 2–3 segundos'],avoid:['dor anterior aguda','carga que altera a técnica'],why:'Permite isolar quadríceps e monitorar amplitude e carga.',subs:['legpressh','legpress'],source:'knee'},
 curl:{name:'Flexora sentada',media:'curl.svg',machine:'Flexora sentada',pattern:'Flexão de joelho',primary:['posteriores de coxa'],level:'iniciante',knee:'adapt',back:'ok',sets:3,reps:'12–15',rest:75,cues:['Eixo alinhado ao joelho','Quadril apoiado','Retorno controlado'],avoid:['dor atrás do joelho'],why:'Fortalece posteriores com suporte do tronco.',subs:['curllying'],source:'acsm'},
 curllying:{name:'Mesa flexora',media:'curl.svg',machine:'Mesa flexora',pattern:'Flexão de joelho',primary:['posteriores de coxa'],level:'iniciante',knee:'adapt',back:'adapt',sets:3,reps:'12–15',rest:75,cues:['Quadril apoiado','Não arqueie a lombar','Controle a volta'],avoid:['desconforto lombar crescente'],why:'Alternativa de mesmo padrão articular da flexora sentada.',subs:['curl'],source:'acsm'},
 hip:{name:'Elevação pélvica na máquina',media:'hip.svg',machine:'Hip thrust / glute drive',pattern:'Extensão de quadril',primary:['glúteos'],level:'iniciante',knee:'ok',back:'adapt',sets:3,reps:'10–15',rest:90,cues:['Queixo levemente recolhido','Costelas controladas','Finalize contraindo glúteos, não a lombar'],avoid:['dor lombar','hiperextensão'],why:'Ênfase em glúteos com suporte e trajetória estável.',subs:['glute'],source:'acsm'},
 abductor:{name:'Cadeira abdutora',media:'abductor.svg',machine:'Cadeira abdutora',pattern:'Abdução de quadril',primary:['glúteo médio'],level:'iniciante',knee:'ok',back:'ok',sets:3,reps:'15–20',rest:60,cues:['Abra sem impulso','Retorne lentamente','Mantenha pés e joelhos alinhados'],avoid:['forçar amplitude final'],why:'Complementa musculatura abdutora do quadril.',subs:['glute'],source:'acsm'},
 glute:{name:'Glúteo máquina',media:'hip.svg',machine:'Glúteo máquina',pattern:'Extensão de quadril',primary:['glúteos'],level:'iniciante',knee:'ok',back:'adapt',sets:3,reps:'12–15',rest:60,cues:['Tronco estável','Movimento pelo quadril','Evite girar a pelve'],avoid:['compensar com lombar'],why:'Extensão de quadril guiada e unilateral.',subs:['hip'],source:'acsm'},
 pulldown:{name:'Puxada frontal',media:'pulldown.svg',machine:'Pulley / puxada alta',pattern:'Puxada vertical',primary:['dorsais','bíceps'],level:'iniciante',knee:'ok',back:'adapt',sets:3,reps:'10–15',rest:75,cues:['Puxe ao alto do peito','Ombros longe das orelhas','Não leve atrás da cabeça'],avoid:['embalo de tronco'],why:'Padrão vertical para costas com carga ajustável.',subs:['row'],source:'acsm'},
 row:{name:'Remada articulada',media:'row.svg',machine:'Remada articulada',pattern:'Puxada horizontal',primary:['costas','bíceps'],level:'iniciante',knee:'ok',back:'ok',sets:3,reps:'10–15',rest:75,cues:['Prefira apoio de peito','Puxe cotovelos para trás','Retorne sem perder postura'],avoid:['embalo lombar'],why:'Puxada horizontal estável, especialmente com apoio de peito.',subs:['pulldown'],source:'acsm'},
 chest:{name:'Supino sentado na máquina',media:'chest.svg',machine:'Chest press',pattern:'Empurrada horizontal',primary:['peitoral','tríceps'],level:'iniciante',knee:'ok',back:'ok',sets:3,reps:'10–15',rest:75,cues:['Costas apoiadas','Punhos neutros','Cotovelos em posição confortável'],avoid:['dor no ombro'],why:'Empurrada guiada com suporte do tronco.',subs:['pecdeck'],source:'acsm'},
 pecdeck:{name:'Peck deck',media:'chest.svg',machine:'Voador / peck deck',pattern:'Adução horizontal do ombro',primary:['peitoral'],level:'iniciante',knee:'ok',back:'ok',sets:3,reps:'12–15',rest:60,cues:['Ombros baixos','Abra somente até amplitude confortável','Sem bater as placas'],avoid:['dor anterior no ombro'],why:'Acessório guiado para peitoral.',subs:['chest'],source:'acsm'},
 shoulder:{name:'Desenvolvimento de ombros',media:'shoulder.svg',machine:'Shoulder press',pattern:'Empurrada vertical',primary:['ombros','tríceps'],level:'iniciante',knee:'ok',back:'adapt',sets:3,reps:'10–12',rest:75,cues:['Costas apoiadas','Não arqueie a lombar','Pare antes de dor'],avoid:['dor no ombro','hiperextensão lombar'],why:'Empurrada vertical guiada e estável.',subs:['lateral'],source:'acsm'},
 lateral:{name:'Elevação lateral na máquina',media:'lateral.svg',machine:'Lateral raise',pattern:'Abdução do ombro',primary:['deltoide lateral'],level:'iniciante',knee:'ok',back:'ok',sets:3,reps:'12–15',rest:60,cues:['Suba até a linha do ombro','Não encolha o pescoço','Carga moderada'],avoid:['dor no ombro'],why:'Acessório guiado para deltoide lateral.',subs:['shoulder'],source:'acsm'},
 armcurl:{name:'Rosca bíceps na máquina',media:'armcurl.svg',machine:'Bíceps máquina / Scott',pattern:'Flexão de cotovelo',primary:['bíceps'],level:'iniciante',knee:'ok',back:'ok',sets:2,reps:'12–15',rest:60,cues:['Cotovelos apoiados','Retorno lento','Não tire o ombro do apoio'],avoid:['balanço do tronco'],why:'Acessório estável para flexores do cotovelo.',subs:[],source:'acsm'},
 triceps:{name:'Tríceps na polia',media:'triceps.svg',machine:'Polia alta',pattern:'Extensão de cotovelo',primary:['tríceps'],level:'iniciante',knee:'ok',back:'adapt',sets:2,reps:'12–15',rest:60,cues:['Cotovelos próximos ao corpo','Tronco estável','Controle a volta'],avoid:['inclinar excessivamente o tronco'],why:'Acessório de tríceps com resistência ajustável.',subs:[],source:'acsm'},
 crunch:{name:'Abdominal na máquina',media:'crunch.svg',machine:'Abdominal machine',pattern:'Flexão controlada do tronco',primary:['abdômen'],level:'iniciante',knee:'ok',back:'adapt',sets:2,reps:'12–15',rest:60,cues:['Expire ao fechar','Aproxime costelas e quadril','Carga que permita controle'],avoid:['dor lombar','puxar apenas com braços'],why:'Trabalho de tronco em trajetória guiada.',subs:[],source:'acsm'},
 calf:{name:'Panturrilha na máquina',media:'calf.svg',machine:'Panturrilha em pé/sentada',pattern:'Flexão plantar',primary:['panturrilhas'],level:'iniciante',knee:'adapt',back:'ok',sets:3,reps:'15–20',rest:60,cues:['Amplitude confortável','Pausa no alto','Movimento pelo tornozelo'],avoid:['travar joelhos'],why:'Complementa força dos flexores plantares.',subs:[],source:'acsm'}
};

const templates={
 2:[{name:'Full body A',ids:['legpressh','curl','chest','row','abductor','crunch']},{name:'Full body B',ids:['extension','hip','pulldown','shoulder','calf','armcurl','triceps']}],
 3:[{name:'Inferiores A',ids:['legpressh','extension','curl','hip','abductor','calf']},{name:'Superiores',ids:['chest','pulldown','row','shoulder','lateral','armcurl','triceps','crunch']},{name:'Inferiores B',ids:['curl','hip','legpress','glute','abductor','calf']}],
 4:[{name:'Inferiores A',ids:['legpressh','extension','curl','hip','abductor','calf']},{name:'Superiores A',ids:['pulldown','row','chest','lateral','armcurl','triceps','crunch']},{name:'Inferiores B',ids:['curl','hip','legpress','glute','abductor','calf']},{name:'Superiores B',ids:['chest','row','pulldown','shoulder','lateral','triceps','crunch']}],
 5:[{name:'Inferiores A',ids:['legpressh','extension','curl','abductor','calf']},{name:'Costas e bíceps',ids:['pulldown','row','armcurl','crunch']},{name:'Glúteos e posterior',ids:['curl','hip','glute','abductor','calf']},{name:'Peito, ombros e tríceps',ids:['chest','pecdeck','shoulder','lateral','triceps']},{name:'Full body leve',ids:['legpressh','row','chest','hip','crunch']}]
};

function blankState(){return {profile:null,plan:null,sessions:[],metrics:[],pain:[],active:null,settings:{theme:'dark'},meta:{createdAt:new Date().toISOString(),version:C.appVersion||'2'}}}
let state=blankState();
function localKey(){return 'emyfit_pro_state_'+(currentUser?.id||'demo')}
function loadLocal(){try{state={...blankState(),...JSON.parse(localStorage.getItem(localKey())||'{}')}}catch{state=blankState()}}
function saveLocal(){localStorage.setItem(localKey(),JSON.stringify(state));scheduleCloudSave()}
let saveTimer=null;function scheduleCloudSave(){if(!cloud||!currentUser)return;clearTimeout(saveTimer);saveTimer=setTimeout(syncUp,700)}
async function syncUp(){if(!cloud||!currentUser)return;const {error}=await cloud.from('user_app_state').upsert({user_id:currentUser.id,data:state,updated_at:new Date().toISOString()});if(error)console.warn(error)}
async function syncDown(){if(!cloud||!currentUser)return false;const {data,error}=await cloud.from('user_app_state').select('data').eq('user_id',currentUser.id).maybeSingle();if(error){console.warn(error);return false}if(data?.data){state={...blankState(),...data.data};localStorage.setItem(localKey(),JSON.stringify(state));return true}return false}

function initCloud(){if(C.supabaseUrl&&C.supabaseAnonKey&&window.supabase){cloud=window.supabase.createClient(C.supabaseUrl,C.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return true}return false}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
function modal(html){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><div class="modal-card"><button class="modal-close" onclick="closeModal()">×</button>${html}</div></div>`)}
function closeModal(){$('#modal')?.remove()}
function setScreen(s){screen=s;renderApp();scrollTo(0,0)}

async function boot(){const has=initCloud();if(has){const {data}=await cloud.auth.getSession();currentUser=data.session?.user||null;cloud.auth.onAuthStateChange(async(_,session)=>{currentUser=session?.user||null;if(currentUser){loadLocal();await syncDown();}renderRoot()})}renderRoot();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js')}
function renderRoot(){if(!currentUser&&!localStorage.getItem('emyfit_demo'))renderAuth();else{loadLocal();if(!state.profile?.onboardingComplete)renderOnboarding();else renderApp()}}

function renderAuth(){
 $('#app').innerHTML=`<div class="auth-page"><div class="auth-card"><div class="auth-logo">${icon('workout')}</div><span class="eyebrow">EMYFIT PRO</span><h1 style="margin:7px 0">Seu treino, com contexto.</h1><p class="muted">Conta, avaliação inicial, treino adaptativo, biblioteca visual e relatórios.</p>
 <div class="auth-tabs"><button class="${authMode==='login'?'active':''}" onclick="authMode='login';renderAuth()">Entrar</button><button class="${authMode==='signup'?'active':''}" onclick="authMode='signup';renderAuth()">Criar conta</button></div>
 ${!cloud?`<div class="notice"><b>Nuvem ainda não configurada.</b><br>O pacote inclui o banco e o login, mas você precisa conectar seu projeto Supabase. Enquanto isso, use o modo de demonstração local.</div>`:''}
 <label>E-mail</label><input id="authEmail" type="email" autocomplete="email" placeholder="voce@email.com"><label>Senha</label><input id="authPass" type="password" autocomplete="current-password" placeholder="mínimo de 8 caracteres">
 <button class="btn primary block" style="margin-top:15px" onclick="submitAuth()">${authMode==='login'?'Entrar':'Criar minha conta'}</button>
 ${authMode==='login'?`<button class="btn ghost block" style="margin-top:9px" onclick="forgotPassword()">Esqueci minha senha</button>`:''}
 ${!cloud?`<button class="btn secondary block" style="margin-top:9px" onclick="startDemo()">Entrar em modo demonstração</button>`:''}
 <p class="small muted" style="margin-top:16px">Os dados de saúde e treino só devem ser usados para personalização e não substituem avaliação profissional.</p></div></div>`
}
async function submitAuth(){if(!cloud)return toast('Configure o Supabase para usar login em nuvem.');const email=$('#authEmail').value.trim(),password=$('#authPass').value;if(password.length<8)return toast('Use uma senha com pelo menos 8 caracteres.');let result=authMode==='login'?await cloud.auth.signInWithPassword({email,password}):await cloud.auth.signUp({email,password});if(result.error)return toast(result.error.message);if(authMode==='signup'&&!result.data.session)return toast('Confira seu e-mail para confirmar a conta.');currentUser=result.data.user;loadLocal();await syncDown();renderRoot()}
async function forgotPassword(){if(!cloud)return;const email=$('#authEmail').value.trim();if(!email)return toast('Informe seu e-mail.');const {error}=await cloud.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});toast(error?error.message:'Link de recuperação enviado.')}
function startDemo(){localStorage.setItem('emyfit_demo','1');currentUser=null;loadLocal();renderRoot()}

const wizard={basic:{},goal:'fatloss',days:4,duration:60,experience:'beginner',preference:'machines',cardio:'bike',limitations:[],screening:[],sleep:'7',stress:'medium'};
function renderOnboarding(){const steps=[stepWelcome,stepBasic,stepGoal,stepRoutine,stepLimits,stepReview];$('#app').innerHTML=`<div class="auth-page"><div class="auth-card" style="width:min(620px,100%)"><div class="stepper">${steps.map((_,i)=>`<span class="${i<=wizardStep?'done':''}"></span>`).join('')}</div>${steps[wizardStep]()}</div></div>`}
function navWizard(n){wizardStep=clamp(wizardStep+n,0,5);renderOnboarding()}
function stepWelcome(){return `<span class="eyebrow">AVALIAÇÃO INICIAL</span><h1>Primeiro entendemos você.</h1><p class="muted">O treino será criado por regras transparentes: objetivo, rotina, experiência, preferência por aparelhos e limitações informadas.</p><div class="source"><b>O que a IA não faz</b><p>Não diagnostica lesões, não substitui professor e não libera exercício diante de sinais de alerta.</p></div><button class="btn primary block" onclick="navWizard(1)">Começar avaliação ${icon('arrow')}</button>`}
function stepBasic(){return `<span class="eyebrow">DADOS BÁSICOS</span><h2>Conte sobre você</h2><div class="grid grid2"><div><label>Nome</label><input id="wName" value="${wizard.basic.name||''}"></div><div><label>Data de nascimento</label><input id="wBirth" type="date" value="${wizard.basic.birth||''}"></div><div><label>Altura (cm)</label><input id="wHeight" type="number" value="${wizard.basic.height||''}"></div><div><label>Peso atual (kg)</label><input id="wWeight" type="number" step=".1" value="${wizard.basic.weight||''}"></div></div><label>Como prefere ser tratada(o)?</label><select id="wGender"><option value="not">Prefiro não informar</option><option value="female">Feminino</option><option value="male">Masculino</option><option value="other">Outro</option></select><div class="row between" style="margin-top:18px"><button class="btn ghost" onclick="navWizard(-1)">Voltar</button><button class="btn primary" onclick="saveBasic()">Continuar</button></div>`}
function saveBasic(){wizard.basic={name:$('#wName').value.trim(),birth:$('#wBirth').value,height:+$('#wHeight').value,weight:+$('#wWeight').value,gender:$('#wGender').value};if(!wizard.basic.name||!wizard.basic.height||!wizard.basic.weight)return toast('Preencha nome, altura e peso.');navWizard(1)}
function selectOne(key,val){wizard[key]=val;renderOnboarding()}
function stepGoal(){const opts=[['fatloss','Emagrecimento','Reduzir gordura preservando força e massa magra.'],['definition','Definição','Melhorar composição corporal e aparência muscular.'],['strength','Força','Aumentar desempenho nos exercícios.'],['health','Saúde e disposição','Criar consistência e condicionamento geral.']];return `<span class="eyebrow">OBJETIVO</span><h2>Qual é a prioridade?</h2><div class="choice-grid">${opts.map(o=>`<button class="choice ${wizard.goal===o[0]?'selected':''}" onclick="selectOne('goal','${o[0]}')"><b>${o[1]}</b><span class="muted small">${o[2]}</span></button>`).join('')}</div><div class="row between" style="margin-top:18px"><button class="btn ghost" onclick="navWizard(-1)">Voltar</button><button class="btn primary" onclick="navWizard(1)">Continuar</button></div>`}
function stepRoutine(){return `<span class="eyebrow">ROTINA</span><h2>Um plano que cabe na vida real</h2><label>Dias disponíveis por semana</label><div class="choice-grid">${[2,3,4,5].map(n=>`<button class="choice ${wizard.days===n?'selected':''}" onclick="selectOne('days',${n})"><b>${n} dias</b><span class="muted small">${n<=3?'Mais recuperação':'Maior distribuição de volume'}</span></button>`).join('')}</div><label>Duração máxima</label><select id="wDuration" onchange="wizard.duration=+this.value"><option value="40">40 minutos</option><option value="50">50 minutos</option><option value="60" selected>60 minutos</option><option value="75">75 minutos</option></select><label>Experiência</label><select id="wExperience" onchange="wizard.experience=this.value"><option value="beginner">Iniciante / retornando</option><option value="intermediate">Intermediário</option><option value="advanced">Avançado</option></select><label>Preferência</label><select id="wPreference" onchange="wizard.preference=this.value"><option value="machines">Principalmente aparelhos</option><option value="mixed">Misto</option></select><div class="row between" style="margin-top:18px"><button class="btn ghost" onclick="navWizard(-1)">Voltar</button><button class="btn primary" onclick="navWizard(1)">Continuar</button></div>`}
function toggleArr(key,val){const a=wizard[key];const i=a.indexOf(val);i>=0?a.splice(i,1):a.push(val);renderOnboarding()}
function stepLimits(){const limits=[['knee','Dor ou limitação nos joelhos'],['back','Dor ou limitação lombar'],['shoulder','Dor ou limitação nos ombros'],['none','Nenhuma limitação relevante']];const red=[['chest','Dor no peito com esforço'],['faint','Desmaio ou tontura importante'],['medical','Restrição médica para exercício'],['acute','Lesão aguda ou cirurgia recente']];return `<span class="eyebrow">SEGURANÇA</span><h2>O que precisamos respeitar?</h2><p class="muted small">Marque tudo que se aplica. Isso não é diagnóstico nem substitui triagem profissional.</p><label>Limitações musculoesqueléticas</label><div class="choice-grid">${limits.map(o=>`<button class="choice ${wizard.limitations.includes(o[0])?'selected':''}" onclick="toggleArr('limitations','${o[0]}')"><b>${o[1]}</b></button>`).join('')}</div><label>Sinais que exigem avaliação antes de progredir</label><div class="choice-grid">${red.map(o=>`<button class="choice ${wizard.screening.includes(o[0])?'selected':''}" onclick="toggleArr('screening','${o[0]}')"><b>${o[1]}</b></button>`).join('')}</div><label>Sono médio</label><select onchange="wizard.sleep=this.value"><option value="lt6">Menos de 6h</option><option value="6">6–7h</option><option value="7" selected>7–8h</option><option value="8">Mais de 8h</option></select><div class="row between" style="margin-top:18px"><button class="btn ghost" onclick="navWizard(-1)">Voltar</button><button class="btn primary" onclick="navWizard(1)">Revisar</button></div>`}
function stepReview(){const risk=wizard.screening.length>0;return `<span class="eyebrow">PLANO PERSONALIZADO</span><h2>Pronto para gerar</h2><div class="grid grid2"><div class="metric"><b>${wizard.days}×</b><span>por semana</span></div><div class="metric"><b>${wizard.duration} min</b><span>por sessão</span></div></div><div class="card flat"><h3>${wizard.basic.name}</h3><p class="muted small">Objetivo: ${goalName(wizard.goal)}<br>Preferência: aparelhos<br>Limitações: ${wizard.limitations.length?wizard.limitations.join(', '):'nenhuma informada'}</p></div>${risk?`<div class="dangerbox"><b>Atenção:</b> você marcou um sinal que pede avaliação profissional antes de aumentar a atividade. O app criará um plano conservador, mas não equivale a liberação médica.</div>`:`<div class="success">Nenhum sinal de alerta foi marcado. Ainda assim, dor nova ou sintomas importantes exigem interrupção e avaliação.</div>`}<button class="btn primary block" style="margin-top:14px" onclick="finishOnboarding()">Gerar meu plano</button><button class="btn ghost block" style="margin-top:8px" onclick="navWizard(-1)">Voltar</button>`}
function goalName(x){return ({fatloss:'Emagrecimento',definition:'Definição',strength:'Força',health:'Saúde e disposição'})[x]}
function generatePlan(p){let days=clamp(+p.days||3,2,5),tpl=JSON.parse(JSON.stringify(templates[days]));const knee=p.limitations.includes('knee'),back=p.limitations.includes('back'),risk=p.screening.length>0;tpl.forEach(w=>{w.id=uid();w.exercises=w.ids.map(id=>{let e=EX[id];if(knee&&id==='legpress')id='legpressh';if(back&&id==='curllying')id='curl';e=EX[id];let sets=e.sets;if(p.experience==='beginner'||risk)sets=Math.max(2,sets-1);return {id,sets,reps:e.reps,rest:e.rest,reason:e.why};});delete w.ids;w.cardio=p.goal==='fatloss'?Math.min(25,10+days*2):12});return {id:uid(),name:`Plano ${days}x — ${goalName(p.goal)}`,createdAt:today(),cycleWeeks:6,days:tpl,basis:['acsm','who','obesity',...(knee?['knee']:[])],status:'active'}}
function finishOnboarding(){state.profile={...wizard.basic,goal:wizard.goal,days:wizard.days,duration:wizard.duration,experience:wizard.experience,preference:wizard.preference,limitations:wizard.limitations,screening:wizard.screening,sleep:wizard.sleep,onboardingComplete:true};state.plan=generatePlan({...state.profile});state.metrics.push({date:today(),weight:state.profile.weight});saveLocal();renderApp();toast('Seu plano foi criado.')}

function shell(content){return `<div class="app-shell"><header class="topbar"><div class="brand"><div class="logo">${icon('workout')}</div><div><b>EmyFit Pro</b><small>PLANO ADAPTATIVO</small></div></div><div class="avatar">${(state.profile?.name||'E').slice(0,1).toUpperCase()}</div></header><main class="main">${content}</main><nav class="bottomnav">${[['home','home','Início'],['workout','workout','Treino'],['coach','coach','Coach'],['reports','chart','Relatórios'],['profile','user','Perfil']].map(x=>`<button class="${screen===x[0]?'active':''}" onclick="setScreen('${x[0]}')">${icon(x[1])}${x[2]}</button>`).join('')}</nav></div>`}
function renderApp(){const fn={home:homeScreen,workout:workoutScreen,coach:coachScreen,reports:reportsScreen,profile:profileScreen}[screen]||homeScreen;$('#app').innerHTML=shell(fn())}
function weekSessions(){let d=new Date();d.setDate(d.getDate()-6);return state.sessions.filter(s=>new Date(s.date)>=d)}
function nextDay(){return state.plan.days[state.sessions.length%state.plan.days.length]}
function homeScreen(){const wk=weekSessions(),next=nextDay(),lastW=state.metrics.at(-1)?.weight||state.profile.weight,adherence=Math.round(wk.length/state.profile.days*100);return `<section class="hero"><span class="eyebrow">BOM TREINO, ${state.profile.name.toUpperCase()}</span><h1>${next.name}</h1><p>${next.exercises.length} exercícios · cardio sugerido ${next.cardio} min</p><button class="btn primary" style="margin-top:18px" onclick="startWorkout('${next.id}')">${icon('play')} Iniciar treino</button></section><div class="grid grid3" style="margin-top:12px"><div class="metric"><b>${wk.length}/${state.profile.days}</b><span>treinos esta semana</span></div><div class="metric"><b>${lastW} kg</b><span>peso registrado</span></div><div class="metric"><b>${avgPain()}/10</b><span>dor média recente</span></div></div><div class="card"><div class="row between"><div><h3>Aderência semanal</h3><span class="muted small">Consistência antes de complexidade.</span></div><b>${clamp(adherence,0,100)}%</b></div><div class="progress" style="margin-top:13px"><span style="width:${clamp(adherence,0,100)}%"></span></div></div><div class="section-title"><h3>Seu plano</h3><span>Ciclo de ${state.plan.cycleWeeks} semanas</span></div>${state.plan.days.map((d,i)=>`<div class="card flat"><div class="row between"><div><span class="eyebrow">DIA ${i+1}</span><h3>${d.name}</h3><span class="muted small">${d.exercises.map(x=>EX[x.id].name).slice(0,3).join(' · ')}${d.exercises.length>3?'…':''}</span></div><button class="btn secondary sm" onclick="viewPlanDay('${d.id}')">Ver ${icon('arrow')}</button></div></div>`).join('')}<div class="card"><h3>Decisão rápida</h3><p class="muted small">Aparelho ocupado? O Coach compara padrão de movimento, musculatura, limitações e histórico antes de sugerir alternativas.</p><button class="btn ghost block" onclick="setScreen('coach')">${icon('coach')} Abrir Coach</button></div>`}
function avgPain(){const a=state.pain.slice(-6);return a.length?(a.reduce((s,x)=>s+(+x.value||0),0)/a.length).toFixed(1):'—'}
function viewPlanDay(id){const d=state.plan.days.find(x=>x.id===id);modal(`<span class="eyebrow">SEU PLANO</span><h2>${d.name}</h2>${d.exercises.map(x=>exercisePreview(x)).join('')}<button class="btn primary block" onclick="closeModal();startWorkout('${d.id}')">Iniciar este treino</button>`)}
function exercisePreview(x){const e=EX[x.id];return `<div class="card flat"><div class="exercise-media"><img src="assets/exercises/${e.media}" alt="Demonstração animada de ${e.name}"></div><div class="row between"><div><h3>${e.name}</h3><span class="muted small">${x.sets} séries · ${x.reps} reps · ${x.rest}s</span></div><span class="pill">${e.machine}</span></div><p class="why">${x.reason}</p><button class="btn ghost sm" onclick="exerciseDetail('${x.id}')">Como executar</button></div>`}

function startWorkout(dayId){const d=state.plan.days.find(x=>x.id===dayId);state.active={id:uid(),dayId,date:today(),startedAt:Date.now(),exercises:d.exercises.map(x=>({id:x.id,sets:Array.from({length:x.sets},()=>({kg:'',reps:'',rir:'',done:false}))})),cardio:d.cardio,painBefore:0};saveLocal();screen='workout';renderApp()}
function workoutScreen(){if(!state.active)return `<section class="hero"><span class="eyebrow">TREINOS</span><h2>Escolha a sessão</h2><p>Seu ciclo foi montado a partir da avaliação inicial.</p></section>${state.plan.days.map((d,i)=>`<div class="card"><div class="row between"><div><span class="eyebrow">DIA ${i+1}</span><h3>${d.name}</h3><span class="muted small">${d.exercises.length} exercícios · ${d.cardio} min cardio</span></div><button class="btn primary sm" onclick="startWorkout('${d.id}')">Iniciar</button></div></div>`).join('')}<div class="card"><h3>Histórico recente</h3>${state.sessions.slice(-4).reverse().map(s=>`<div class="row between" style="padding:10px 0;border-bottom:1px solid var(--line)"><div><b>${s.name}</b><div class="muted small">${fmt(s.date)} · ${s.duration} min</div></div><span class="pill ${s.painAfter>=5?'bad':'good'}">dor ${s.painAfter}/10</span></div>`).join('')||'<p class="muted">Nenhum treino concluído ainda.</p>'}</div>`;const d=state.plan.days.find(x=>x.id===state.active.dayId),done=state.active.exercises.filter(x=>x.sets.every(s=>s.done)).length;return `<section class="hero"><span class="eyebrow">TREINO EM ANDAMENTO</span><h2>${d.name}</h2><p>${done} de ${state.active.exercises.length} exercícios concluídos.</p></section>${state.active.exercises.map((x,i)=>activeExercise(x,i)).join('')}<div class="card"><h3>Finalização</h3><label>Cardio realizado (min)</label><input id="finishCardio" type="number" value="${state.active.cardio}"><label>Dor no joelho após o treino: <b id="painVal">0/10</b></label><input id="finishPain" type="range" min="0" max="10" value="0" oninput="painVal.textContent=this.value+'/10'"><label>Esforço geral</label><select id="finishRpe"><option value="5">5 — leve</option><option value="6">6 — moderado</option><option value="7" selected>7 — desafiador e controlado</option><option value="8">8 — difícil</option><option value="9">9 — muito difícil</option></select><label>Observações</label><textarea id="finishNotes" placeholder="Dor, máquina ocupada, execução, energia..."></textarea><button class="btn primary block" style="margin-top:13px" onclick="finishWorkout()">${icon('check')} Concluir treino</button><button class="btn danger block" style="margin-top:8px" onclick="cancelWorkout()">Cancelar sessão</button></div>${restSeconds>0?`<div class="restbar"><div><span class="eyebrow">DESCANSO</span><div class="timer" id="restDisplay">${timeText(restSeconds)}</div></div><button class="btn secondary sm" onclick="stopRest()">Pular</button></div>`:''}`}
function activeExercise(x,ei){const e=EX[x.id],complete=x.sets.every(s=>s.done);return `<div class="card workout-card"><div class="exercise-media"><img src="assets/exercises/${e.media}" alt="Animação de ${e.name}"></div><div class="exercise-row"><div><div class="row wrap"><span class="pill">${e.machine}</span><span class="pill ${complete?'good':''}">${complete?'concluído':e.pattern}</span></div><h3 style="margin-top:9px">${e.name}</h3><p class="why">${e.why}</p></div><button class="btn secondary sm" onclick="exerciseDetail('${x.id}')">${icon('info')}</button></div><div class="row wrap"><button class="btn ghost sm" onclick="replacement('${x.id}',${ei})">Máquina ocupada</button><button class="btn ghost sm" onclick="startRest(${e.rest})">${icon('clock')} ${e.rest}s</button></div><div class="set-head"><span>#</span><span>kg</span><span>reps</span><span>RIR</span><span></span></div>${x.sets.map((s,si)=>`<div class="set-row"><b>${si+1}</b><input inputmode="decimal" value="${s.kg}" placeholder="kg" onchange="setValue(${ei},${si},'kg',this.value)"><input inputmode="numeric" value="${s.reps}" placeholder="reps" onchange="setValue(${ei},${si},'reps',this.value)"><input inputmode="numeric" value="${s.rir}" placeholder="2" onchange="setValue(${ei},${si},'rir',this.value)"><button class="set-check ${s.done?'done':''}" onclick="toggleSet(${ei},${si},${e.rest})">${s.done?icon('check'):'○'}</button></div>`).join('')}</div>`}
function setValue(ei,si,k,v){state.active.exercises[ei].sets[si][k]=v;saveLocal()}
function toggleSet(ei,si,rest){const s=state.active.exercises[ei].sets[si];s.done=!s.done;saveLocal();if(s.done)startRest(rest);renderApp()}
function startRest(sec){stopRest();restSeconds=sec;restTimer=setInterval(()=>{restSeconds--;const d=$('#restDisplay');if(d)d.textContent=timeText(restSeconds);if(restSeconds<=0){stopRest();toast('Descanso concluído.')}},1000);renderApp()}
function stopRest(){clearInterval(restTimer);restTimer=null;restSeconds=0;renderApp()}
function timeText(n){return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
function finishWorkout(){const a=state.active,d=state.plan.days.find(x=>x.id===a.dayId),pain=+$('#finishPain').value||0;state.sessions.push({id:a.id,date:a.date,name:d.name,dayId:d.id,duration:Math.max(1,Math.round((Date.now()-a.startedAt)/60000)),cardio:+$('#finishCardio').value||0,painAfter:pain,rpe:+$('#finishRpe').value,notes:$('#finishNotes').value,exercises:a.exercises});state.pain.push({date:a.date,value:pain});state.active=null;saveLocal();stopRest();screen='reports';renderApp();toast('Treino salvo e sincronizado.')}
function cancelWorkout(){if(confirm('Cancelar o treino em andamento?')){state.active=null;saveLocal();renderApp()}}

function exerciseDetail(id){const e=EX[id],src=EVIDENCE[e.source];modal(`<span class="eyebrow">BIBLIOTECA DE EXERCÍCIOS</span><h2>${e.name}</h2><div class="exercise-media" style="height:230px"><img src="assets/exercises/${e.media}" alt="Animação de ${e.name}"></div><div class="grid grid2"><div class="metric"><b>${e.machine}</b><span>aparelho</span></div><div class="metric"><b>${e.reps}</b><span>faixa sugerida</span></div></div><h3>Execução</h3><ol>${e.cues.map(c=>`<li>${c}</li>`).join('')}</ol><div class="notice"><b>Interrompa e reavalie se:</b><br>${e.avoid.join(' · ')}</div><div class="source"><b>${src.title}</b><p>${src.note}</p></div><p class="muted small">A animação é esquemática. O modelo e os ajustes da máquina podem variar; peça ao professor para regular banco, eixo e amplitude.</p>`)}
function compatible(a,b){let score=0;if(a.pattern===b.pattern)score+=55;score+=a.primary.filter(x=>b.primary.includes(x)).length*18;if(b.knee==='ok'||b.knee==='adapt')score+=5;if(b.back==='ok'||b.back==='adapt')score+=5;return clamp(score,0,100)}
function blocked(e){const l=state.profile.limitations||[];return (l.includes('knee')&&e.knee==='avoid')||(l.includes('back')&&e.back==='avoid')}
function getSubs(id){const a=EX[id];return Object.entries(EX).filter(([k,e])=>k!==id&&!blocked(e)).map(([id,e])=>({id,e,score:compatible(a,e)})).filter(x=>x.score>=45).sort((x,y)=>y.score-x.score).slice(0,3)}
function replacement(id,index=null){const e=EX[id],subs=getSubs(id);modal(`<span class="eyebrow">SUBSTITUIÇÃO ANALISADA</span><h2>${e.name} está ocupado</h2><p class="muted">A pontuação considera padrão de movimento e músculos. Uma troca nunca é automaticamente idêntica.</p>${subs.length?subs.map(s=>`<div class="card flat"><div class="row between"><div><h3>${s.e.name}</h3><span class="muted small">${s.e.machine} · ${s.e.pattern}</span></div><b>${s.score}%</b></div><div class="score" style="margin:10px 0"><span style="width:${s.score}%"></span></div><p class="small muted">${s.e.pattern===e.pattern?'Mantém o padrão principal.':'Padrão relacionado, com distribuição muscular diferente.'}</p>${index!==null?`<button class="btn primary sm" onclick="applyReplacement(${index},'${s.id}')">Usar no treino</button>`:''}</div>`).join(''):`<div class="notice">Não há alternativa suficientemente equivalente na biblioteca. Aguarde o aparelho ou consulte o professor.</div>`}<div class="source"><b>Regra de segurança</b><p>Se a troca elevar dor, alterar muito a técnica ou exigir um movimento não treinado, ela deve ser recusada.</p></div>`)}
function applyReplacement(i,id){state.active.exercises[i]={id,sets:Array.from({length:EX[id].sets},()=>({kg:'',reps:'',rir:'',done:false}))};saveLocal();closeModal();renderApp();toast('Substituição aplicada.')}

function coachScreen(){return `<section class="hero"><span class="eyebrow">COACH INTELIGENTE</span><h2>Decisão explicada, não improvisada.</h2><p>O modo offline usa regras da biblioteca. A IA generativa pode ser conectada no backend sem expor a chave no aplicativo.</p></section><div class="card"><label>Exercício atual</label><select id="coachEx">${Object.entries(EX).map(([id,e])=>`<option value="${id}">${e.name}</option>`).join('')}</select><label>O que aconteceu?</label><select id="coachIntent"><option value="occupied">A máquina está ocupada</option><option value="load">Quero saber se aumento a carga</option><option value="pain">Senti dor durante o exercício</option><option value="technique">Quero revisar a execução</option></select><label>Dor agora (0–10)</label><input id="coachPain" type="range" min="0" max="10" value="0"><label>Pergunta adicional</label><textarea id="coachQuestion" placeholder="Ex.: só tenho leg press horizontal disponível"></textarea><button class="btn primary block" style="margin-top:13px" onclick="coachAnswer()">${icon('coach')} Analisar</button></div><div id="coachResult"></div><div class="card"><h3>Limites do Coach</h3><p class="muted small">Não diagnostica, não prescreve tratamento e não substitui avaliação presencial. Em dor forte, inchaço, travamento, sintomas cardiopulmonares ou piora progressiva, a resposta correta é interromper e buscar avaliação.</p></div>`}
async function coachAnswer(){const id=$('#coachEx').value,intent=$('#coachIntent').value,pain=+$('#coachPain').value,q=$('#coachQuestion').value,e=EX[id],box=$('#coachResult');box.innerHTML='<div class="card"><p class="muted">Analisando contexto…</p></div>';if(pain>=5||intent==='pain'&&pain>=4){box.innerHTML=`<div class="assistant-msg ai"><b>Interrompa este exercício agora.</b><p>Dor moderada/forte não deve ser “compensada” com outra máquina sem avaliação. Reduza a atividade e procure o professor; sinais como inchaço, travamento ou dor persistente exigem avaliação de saúde.</p></div>`;return}if(C.aiFunctionUrl&&cloud&&currentUser&&q.trim()){try{const {data:{session}}=await cloud.auth.getSession();const r=await fetch(C.aiFunctionUrl,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`},body:JSON.stringify({question:q,exercise:e,profile:state.profile,recentSessions:state.sessions.slice(-5)})});if(r.ok){const d=await r.json();box.innerHTML=`<div class="assistant-msg ai">${d.answer}</div>`;return}}catch(err){console.warn(err)}}let html='';if(intent==='occupied'){const subs=getSubs(id);html=`<div class="assistant-msg ai"><b>Melhor opção cadastrada: ${subs[0]?.e.name||'nenhuma'}</b><p>${subs[0]?`Compatibilidade ${subs[0].score}%. ${subs[0].e.pattern===e.pattern?'Mantém o padrão principal de movimento.':'O estímulo é relacionado, mas não idêntico.'}`:'A biblioteca não encontrou equivalência segura.'}</p><button class="btn ghost sm" onclick="replacement('${id}')">Ver alternativas</button></div>`}else if(intent==='load'){const hist=exerciseHistory(id);const ok=hist.length>=2&&hist.slice(-2).every(h=>h.avgRir>=2&&h.pain<3&&h.completed);html=`<div class="assistant-msg ai"><b>${ok?'Progressão mínima pode ser considerada.':'Ainda não recomendo aumentar.'}</b><p>${ok?'Você completou as duas últimas exposições com margem de repetições, baixa dor e séries completas. Aumente apenas o menor incremento da máquina e reavalie técnica e dor.':'Precisamos de pelo menos duas sessões estáveis: topo da faixa de repetições, RIR em torno de 2–3, sem piora de dor e execução consistente.'}</p></div>`}else if(intent==='technique'){html=`<div class="assistant-msg ai"><b>${e.name}</b><ol>${e.cues.map(x=>`<li>${x}</li>`).join('')}</ol></div>`}else html=`<div class="assistant-msg ai"><b>Não force a repetição.</b><p>Reduza carga e amplitude. Se a dor voltar ou persistir, interrompa o exercício e peça avaliação.</p></div>`;box.innerHTML=html}
function exerciseHistory(id){return state.sessions.map(s=>{const x=s.exercises.find(e=>e.id===id);if(!x)return null;const done=x.sets.filter(a=>a.done),rirs=done.map(a=>+a.rir).filter(Number.isFinite);return {completed:done.length===x.sets.length,avgRir:rirs.length?rirs.reduce((a,b)=>a+b,0)/rirs.length:0,pain:s.painAfter}}).filter(Boolean)}

function reportsScreen(){const sessions=state.sessions,mins=sessions.reduce((a,s)=>a+s.duration,0),cardio=sessions.reduce((a,s)=>a+s.cardio,0),metrics=state.metrics.slice(-10);return `<section class="hero"><span class="eyebrow">RELATÓRIOS</span><h2>Progresso de fácil leitura.</h2><p>Treino, peso, volume, aderência e dor no mesmo painel.</p></section><div class="grid grid3" style="margin-top:12px"><div class="metric"><b>${sessions.length}</b><span>treinos concluídos</span></div><div class="metric"><b>${mins}</b><span>min de força</span></div><div class="metric"><b>${cardio}</b><span>min de cardio</span></div></div><div class="card"><div class="row between"><div><h3>Peso</h3><span class="muted small">Últimos registros</span></div><button class="btn secondary sm" onclick="metricModal()">${icon('plus')} Registrar</button></div>${weightChart(metrics)}</div><div class="card"><h3>Volume por sessão</h3>${volumeChart(sessions.slice(-8))}</div><div class="card"><h3>Dor após o treino</h3>${painChart(state.pain.slice(-10))}</div><div class="card"><h3>Evolução por exercício</h3><select id="reportEx" onchange="renderExerciseReport(this.value)">${Object.entries(EX).map(([id,e])=>`<option value="${id}">${e.name}</option>`).join('')}</select><div id="exerciseReport">${exerciseReportHtml('legpressh')}</div></div><div class="card"><h3>Histórico</h3>${sessions.slice().reverse().map(s=>`<div class="row between" style="padding:11px 0;border-bottom:1px solid var(--line)"><div><b>${s.name}</b><div class="muted small">${fmt(s.date)} · ${s.duration} min · cardio ${s.cardio} min</div></div><button class="btn secondary sm" onclick="sessionDetail('${s.id}')">Ver</button></div>`).join('')||'<p class="muted">Seu relatório aparece após o primeiro treino.</p>'}</div>`}
function weightChart(a){if(!a.length)return '<p class="muted">Sem dados.</p>';const vals=a.map(x=>+x.weight),min=Math.min(...vals)-1,max=Math.max(...vals)+1;return `<div class="chart">${a.map(x=>`<div class="chartbar" style="height:${35+(x.weight-min)/(max-min||1)*120}px"><b>${x.weight}</b><small>${fmt(x.date)}</small></div>`).join('')}</div>`}
function sessionVolume(s){return s.exercises.reduce((sum,e)=>sum+e.sets.reduce((a,x)=>a+(x.done?(+x.kg||0)*(+x.reps||0):0),0),0)}
function volumeChart(a){if(!a.length)return '<p class="muted">Sem dados.</p>';const vals=a.map(sessionVolume),max=Math.max(...vals,1);return `<div class="chart">${a.map((x,i)=>`<div class="chartbar" style="height:${25+vals[i]/max*135}px"><b>${Math.round(vals[i])}</b><small>${fmt(x.date)}</small></div>`).join('')}</div><p class="muted small">Volume = carga × repetições das séries registradas. Serve para acompanhar tendência, não para comparar exercícios diferentes.</p>`}
function painChart(a){if(!a.length)return '<p class="muted">Sem dados.</p>';return `<svg class="linechart" viewBox="0 0 640 210"><path d="M35 175H610M35 25V175" stroke="#384145" fill="none"/>${a.map((x,i)=>{const px=45+i*(550/Math.max(1,a.length-1)),py=175-(+x.value||0)*14;return `${i?`<line x1="${45+(i-1)*(550/Math.max(1,a.length-1))}" y1="${175-(+a[i-1].value||0)*14}" x2="${px}" y2="${py}" stroke="#d5a277" stroke-width="4"/>`:''}<circle cx="${px}" cy="${py}" r="7" fill="#f0d2bd"/><text x="${px}" y="200" text-anchor="middle" fill="#9ba4a7" font-size="11">${fmt(x.date)}</text>`}).join('')}</svg>`}
function exerciseReportHtml(id){const h=exerciseHistory(id);if(!h.length)return '<p class="muted">Ainda não há registros deste exercício.</p>';return `<div class="grid grid2" style="margin-top:11px"><div class="metric"><b>${h.length}</b><span>sessões registradas</span></div><div class="metric"><b>${h.at(-1).avgRir.toFixed(1)}</b><span>RIR médio recente</span></div></div><p class="muted small">${h.length>=2&&h.slice(-2).every(x=>x.completed&&x.pain<3&&x.avgRir>=2)?'Tendência estável: progressão mínima pode ser avaliada.':'Mantenha a carga até consolidar execução, repetições e baixa dor.'}</p>`}
function renderExerciseReport(id){$('#exerciseReport').innerHTML=exerciseReportHtml(id)}
function metricModal(){modal(`<span class="eyebrow">NOVO REGISTRO</span><h2>Peso e medidas</h2><label>Data</label><input id="mDate" type="date" value="${today()}"><label>Peso (kg)</label><input id="mWeight" type="number" step=".1"><div class="grid grid2"><div><label>Cintura (cm)</label><input id="mWaist" type="number" step=".1"></div><div><label>Abdômen (cm)</label><input id="mAbd" type="number" step=".1"></div><div><label>Quadril (cm)</label><input id="mHip" type="number" step=".1"></div><div><label>Coxa (cm)</label><input id="mThigh" type="number" step=".1"></div></div><button class="btn primary block" style="margin-top:14px" onclick="saveMetric()">Salvar registro</button>`)}
function saveMetric(){const weight=+$('#mWeight').value;if(!weight)return toast('Informe o peso.');state.metrics.push({date:$('#mDate').value,weight,waist:+$('#mWaist').value||null,abd:+$('#mAbd').value||null,hip:+$('#mHip').value||null,thigh:+$('#mThigh').value||null});state.metrics.sort((a,b)=>a.date.localeCompare(b.date));saveLocal();closeModal();renderApp();toast('Métrica salva.')}
function sessionDetail(id){const s=state.sessions.find(x=>x.id===id);modal(`<span class="eyebrow">SESSÃO CONCLUÍDA</span><h2>${s.name}</h2><p class="muted">${fmt(s.date)} · ${s.duration} min · dor ${s.painAfter}/10</p>${s.exercises.map(x=>`<div class="card flat"><h3>${EX[x.id].name}</h3><p class="muted small">${x.sets.map((a,i)=>`${i+1}: ${a.kg||'—'} kg × ${a.reps||'—'} · RIR ${a.rir||'—'}`).join('<br>')}</p></div>`).join('')}<p><b>Observações:</b> ${s.notes||'Nenhuma'}</p>`)}

function profileScreen(){const p=state.profile;return `<section class="hero"><span class="eyebrow">PERFIL</span><h2>${p.name}</h2><p>${goalName(p.goal)} · ${p.days} dias por semana · ${p.preference==='machines'?'aparelhos':'misto'}</p></section><div class="card"><h3>Dados pessoais</h3><label>Nome</label><input id="pName" value="${p.name}"><div class="grid grid2"><div><label>Altura (cm)</label><input id="pHeight" type="number" value="${p.height}"></div><div><label>Peso-base (kg)</label><input id="pWeight" type="number" step=".1" value="${p.weight}"></div></div><label>Limitações registradas</label><input value="${p.limitations.join(', ')||'Nenhuma'}" disabled><button class="btn primary block" style="margin-top:14px" onclick="saveProfile()">Salvar alterações</button></div><div class="card"><h3>Conta e sincronização</h3>${currentUser?`<div class="success">${icon('cloud')} Sincronização em nuvem ativa para <b>${currentUser.email}</b>.</div><button class="btn ghost block" style="margin-top:10px" onclick="forceSync()">Sincronizar agora</button><button class="btn danger block" style="margin-top:8px" onclick="logout()">${icon('logout')} Sair</button>`:`<div class="notice">Modo local. Os dados não voltarão automaticamente em outro celular até o Supabase ser configurado e você entrar com uma conta.</div><button class="btn ghost block" style="margin-top:10px" onclick="exitDemo()">Configurar login</button>`}</div><div class="card"><h3>Base científica</h3>${state.plan.basis.map(k=>{let s=EVIDENCE[k];return `<div class="source"><b>${s.title}</b><p>${s.note}</p></div>`}).join('')}<p class="muted small">Biblioteca v2.0 · revisão julho/2026. Para disponibilização pública, cada regra e exercício deve passar por revisão formal de profissional de Educação Física.</p></div><div class="card"><h3>Plano</h3><button class="btn secondary block" onclick="regeneratePlan()">Regerar plano com os dados atuais</button><button class="btn ghost block" style="margin-top:8px" onclick="exportBackup()">Exportar backup</button></div>`}
function saveProfile(){state.profile.name=$('#pName').value.trim();state.profile.height=+$('#pHeight').value;state.profile.weight=+$('#pWeight').value;saveLocal();toast('Perfil atualizado.');renderApp()}
async function forceSync(){await syncUp();toast('Dados sincronizados.')}
async function logout(){if(cloud)await cloud.auth.signOut();currentUser=null;screen='home';renderRoot()}
function exitDemo(){localStorage.removeItem('emyfit_demo');currentUser=null;renderRoot()}
function regeneratePlan(){if(confirm('Gerar um novo ciclo com base no perfil atual? O histórico será preservado.')){state.plan=generatePlan(state.profile);saveLocal();screen='home';renderApp();toast('Novo ciclo gerado.')}}
function exportBackup(){const a=document.createElement('a'),b=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});a.href=URL.createObjectURL(b);a.download='emyfit-pro-backup.json';a.click();URL.revokeObjectURL(a.href)}

boot();
